job_arrival_lambda: 0.65

dd:
  min: 30
  max: 50

families:
  f1:
    weight: 0.1
    routing: [ 1, 1, 0, 1, 1, 1 ]
    processing:
      alpha: 2
      beta: 2
  f2:
    weight: 0.52
    routing: [ 0.8, 0.8, 1, 0.8, 0.8, 0.75 ]
    processing:
      alpha: 4
      beta: 0.5
  f3:
    weight: 0.38
    routing: [ 0, 0, 1, 0, 0, 0.75 ]
    processing:
      alpha: 6
      beta: 1/6


throughput_sampling: True
throughput_timestep: 30  # da valutare

wip_sampling: True
wip_timestep: 1  # da valutare

mean_time_in_system_sampling: False
mean_time_in_system_timestep: 30  # da valutare

mean_delay_in_system_sampling: False
mean_delay_in_system_timestep: 30  # da valutare

reward:
  reward_sampling: True
  reward_time_step: 1  # da valutare
  delivery_half_window: 10  # da valutare
  daily_penalty: 2  # da valutare
  award_delivery: 400  # da valutare
  wip_penalty: 0.15  # se la coda aumenta di 1, il reward diminuisce
  wip_award: 0.25  # da valutare
