job_arrival_lambda: 0.65

dd:  # due date
  min: 30
  max: 50

families:
  f1:
    weight: 0.1
    routing: [ 1, 1, 0, 1, 1, 1 ]
    processing:
      alpha: 2
      beta: 2
  f2:
    weight: 0.52
    routing: [ 0.8, 0.8, 1, 0.8, 0.8, 0.75 ]
    processing:
      alpha: 4
      beta: 0.5
  f3:
    weight: 0.38
    routing: [ 0, 0, 1, 0, 0, 0.75 ]
    processing:
      alpha: 6
      beta: 1/6


throughput_sampling: True
throughput_timestep: 30  # one month

wip_sampling: True
wip_timestep: 1  # one day

mean_time_in_system_sampling: False
mean_time_in_system_timestep: 30  # one month

mean_delay_in_system_sampling: False
mean_delay_in_system_timestep: 30  # one month

reward:
  reward_sampling: True
  reward_time_step: 1  # one day
  delivery_half_window: 7  # delivery tolerance time window
  daily_penalty: 5  # daily penalty of delivery outside the tolerance window
  award_delivery: 125  # in case of proper delivery
  wip_penalty: 15  # if a queue grows, the reward is reduced
  wip_award: 2  # if a queue gets shorter, the reward increases
  avoid_empty_queue_penalty: 125  # to prevent production from freezing
  job_late_penalty: 0  # additional penalty for job in psp late

